# Generated by Django 4.2.3 on 2023-07-10 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cards",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pan", models.CharField(max_length=20)),
                ("expiration_date", models.CharField(max_length=20)),
                ("cvv", models.CharField(max_length=4)),
                ("issue_date", models.DateTimeField(auto_now_add=True)),
                ("owner_id", models.UUIDField(default=uuid.uuid4)),
                ("status", models.CharField(max_length=10)),
            ],
        ),
    ]
